language: python
python: '2.6'
env:
  global:
  - secure: Ni1opL+3wD8A2qBcFUZ9oY8zeblloyPy/LFb981qFQsGAXWwDnaa7i/2yxQXFXP2ahTUojflp7icDvBwWpV8Tc48JMJDOQLvxSaijiSpYdzx4m1FLXufv7kdgeuvYsLcBk4+vhqPTZaX4JADubj0V+/AJThupYG9XF5r3LfU2DjgRwxpRQthShgb81cKTMVYqdhq4/A533SFLuYVou/PlkywYNcwp9QHVI8bzw8XlRPkzJoPcH2871yfOofQgQp7l96cFbEXhU027y3sBDKzz/Rm/pEysw71EyPqlJiZxn5rHwhXcv0eZ8KcwxZ5c6bPh1rDYYj5CxRqzXXuHRL60Hvwfd6FiWAb4tZo3NNDYamc1yDq4pLdkKHGqmhf44cNBcCegs4Myn2WKUt/dSWegoHvBlZNxNWcirBLxOQbfvTyEqJ60Hh5FBWtG0hCNMio4bUmWm47w6SzucCpzIe4gENqQ9d++ObskpQ9fFrJsW1qPcHDOZzpg/0aHhd4QN61a0ycQMd2g6USlzmjjZSFVXmbu11kWKbADP/QhSmpiKoXiFY1sYvo3IGKYZaj9PxiucGtpGynplFgE006ymf2v70evjrY+FmUdFX353w0wefOFCmx3Ukx9T16YwNn8CuZDIW3Jdx5zhzl8lomF7FuLH7SUTK2xoQiHkQBnaM3B/I=
  - secure: YD8QucufBppGWj9yKYvdDGKD5fFOE6H7xHYfSCpRbSdvMlOu5WAuuoCr+ie6GonZse+fqRidWdOOTxgtjqSAxR76wal2DaCPXwW+XHCjDOylYtmDpI33bwibXvc9hB83w/2CNuzrNeeTTqKjh6QzAlgJ5e9sHVSG04u4uF4qIxVAxkygHmetrPofSsUMJXkJ6Vdz4MYcIccw+pT7DiSGgNGnv/KPES1bSGCjS2Tj8jRYt7583WkL41BX7Atmnzk7/sM9B/hIv+m1xyLShao8UaPdbTVJl5LMKI20NXZXkUWwWvYrzMZ6Xi2O83lce8YnLYBk37n7A/YXux9vT818TYUcXrpab0qhBal67+L1c4m/2iDRYq5L+pPkjw9ftslN5zR8gqBN6c/ZTf0QSrNmtUjr8dyFKgVjFAMYb4Rth0yJReU6O/xFyyj4rFOUTjESYviCN9Dxj5Spznx2S4ayuIIXBAhDKYTDG0vQOQbdBeOiuwkqh/y63/XPihPxwuXPO1QpzrJGFiEgtmv21mHOr2pX2t9IlKJcDbRLHUAjzptbjDej+gdO7s1xe1+8kwRgiU+LuxzzviNSY9rmQTfIlJRRUvElkPyxCGmSE6DMVMpNrxQiHLJ5SoBeEP6RE00Wlk2qk9TOLIoNPowGa3sxEOYOsGDlmaIxurduat9rsAY=
  - secure: gyohNCKlSJstKRnf3ocfGG4nlaDYr1R3G124OEGlXUtJiochlJ3piFFKmMmLiGQ/fj8c7/jK6LUYoUxK91jPu6CCrh0Y9RkawyuL4b7wlADRJtYzRVBTIvXlIKw3hNGTWwe3ltn2AcRC6Un3FbYWYoUX/fkJa1MCrx+V2fJSfBD1nGHk3Ci86Kk8xfEOBl4OpdMkzyF6ikeD/Y8f+ONHXZGdYxpooYRcI+8D34hrr7oN0x3fbBaV3jIj1mIKb63R137IMAhW/iqUPwHQfSxz8NVeoXE82PL5jrUAXhnzBWlvu+8pt6EB26Rgri+45qJMEGLjjVH5V6CQNFmnLhAClbniCXUyauakOQwBHLAwcCMNoc03ZNajkzugh0hWohudx0tbwMXa3aUrRijHOM3kjwVsGenjlnazPk1JL/UGzgLe8DGffPe9xPZNBXNnlPoiid5B5iZB39xTNaqwg1HA8utmX2j13JThgE127s0ToNaCEaZd7RyW8RRL81hIRhVrv/RCpmOH8nt1Oi4BaBQRTiSU0cHXSliI3Ki7lY2p7OSiEdD9O+5u+5HbSXJXLbL7dKBq0FxLJPbg+0xuCstomHnYiTqyI3ca1ntWyy3TvlM46yr1x+3wFOozez6kYhjSGt3iDGEyfzTEa9K9Gi2RRaZTWToECLHcw8WNHxL4rYA=
  - secure: RZsAPNMP3uMPAzpETHe9g2PBdfh8jMT7/jPjSLOb9c2H9tVbzfahxngOBnFYpfPfY0iJmkvZZglnE2EQm1AgCpc8G7OGnhOAQZ3RBFJHGhBGifawAYsPks3aFYd33F/u8it7KX6qGLKBXnZ5s8f7jfif/Qbd0ClmBtBx3L1/hBK4bLiMHvI11thY4Pw68W9+eLCUGMa2o1Z30wOSQIRxd6GkA4BuCfbs8SKa5Yr12u9Ao4fiiaAGTwLvHzltgHd2b8hQm91vcGTKKWKFBbDhfDqR91XZX06ZKksuy+tvEyVFen358l9yrklMSBGx3g3dcNno3zWDoe6odn9cN7gf98ZJCg+Z0yAoDyxKvCpkse19qZJOcfUeET0QCbW6IGXy2yJYdsMdLXI5DbYW9z4QTcFyLsHk8hLnGhuwHsC8KM4IrvG5RieWjGTCRnduQrwWwwSZgBrva54UK0UN1vXjxsOqxrWNfMBSwB8xPVefs/i8HvUcmV8PV/Bnk4INeNBPQOasHzKNPr/JETjSBkSyeia7MTWPGGCx8nDDHgbAVx2UgftrItghpDhC8euUK3lZ6Dhh/PI4qMq/THagYE0jqW/gT/QR/UeY8uxIAQXffF9xX6Ovyt0OogH8u0b7EsHB3x+FRW56OXnxzXdl9c6IZylE25tYRrQx2ySkWepMCus=
install:
- pip install MySQL-python
script:
- cp server/config_example.py server/config.py
- python server/next.cgi
- npm install gulp
- npm install gulp -g
- npm install vinyl-ftp gulp-util minimist --save-dev
- chmod +x staging.sh
- "./staging.sh  $STAGING_FTP_USER  $STAGING_FTP_PASSWORD"
before_deploy:
- rm server/config.py
- chmod +x deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh  $FTP_USER  $FTP_PASSWORD  $TRAVIS_TAG"
  on:
    tags: true
